# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr:
  - feature/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Agent Setup'
    steps:
      - task: DockerInstaller@0
        inputs:
          dockerVersion: '19.03.1'

  - stage: 'Build Application'
    steps:
      - script: docker-compose build
